import 'denver_model.dart';

/// Database 125 Item Skrining Perkembangan Denver II (Bahasa Indonesia)
class DenverData {
  static final List<DenverItem> allItems = _buildItemList();

  static List<DenverItem> getItemsBySector(DenverSector sector) {
    return allItems.where((item) => item.sector == sector).toList()
      ..sort((a, b) => a.indexInSector.compareTo(b.indexInSector));
  }

  static DenverItem? getItemById(String id) {
    try {
      return allItems.firstWhere((item) => item.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<DenverItem> _buildItemList() {
    final List<DenverItem> items = [];

    // =========================================================================
    // 1. PERSONAL SOSIAL
    // =========================================================================
    items.addAll([
      const DenverItem(
        id: 'ps_1',
        sector: DenverSector.personalSocial,
        title: 'Menatap Muka',
        instructions: 'Pemeriksa/orang tua menatap wajah anak dari jarak 30 cm.',
        p25: 0.1, p50: 0.5, p75: 1.0, p90: 1.5,
        reportableByParent: false,
        indexInSector: 0,
      ),
      const DenverItem(
        id: 'ps_2',
        sector: DenverSector.personalSocial,
        title: 'Tersenyum Responsif',
        instructions: 'Senyumi anak dan bicara padanya. Apakah anak tersenyum balik?',
        p25: 0.5, p50: 1.0, p75: 1.5, p90: 2.0,
        reportableByParent: true,
        indexInSector: 1,
      ),
      const DenverItem(
        id: 'ps_3',
        sector: DenverSector.personalSocial,
        title: 'Tersenyum Spontan',
        instructions: 'Anak tersenyum sendiri tanpa dirangsang sentuhan/suara.',
        p25: 0.8, p50: 1.2, p75: 1.8, p90: 2.3,
        reportableByParent: true,
        indexInSector: 2,
      ),
      const DenverItem(
        id: 'ps_4',
        sector: DenverSector.personalSocial,
        title: 'Mengamati Tangannya',
        instructions: 'Anak memandang tangannya sendiri setidaknya beberapa detik.',
        p25: 1.5, p50: 2.2, p75: 3.0, p90: 3.8,
        reportableByParent: true,
        indexInSector: 3,
      ),
      const DenverItem(
        id: 'ps_5',
        sector: DenverSector.personalSocial,
        title: 'Berusaha Mencapai Mainan',
        instructions: 'Letakkan mainan di dekat anak, amati apakah anak berusaha meraih.',
        p25: 3.0, p50: 4.0, p75: 5.0, p90: 5.8,
        reportableByParent: false,
        indexInSector: 4,
      ),
      const DenverItem(
        id: 'ps_6',
        sector: DenverSector.personalSocial,
        title: 'Makan Sendiri',
        instructions: 'Anak bisa memegang dan memasukkan biskuit/makanan ke mulut.',
        p25: 4.5, p50: 5.5, p75: 6.5, p90: 7.8,
        reportableByParent: true,
        indexInSector: 5,
      ),
      const DenverItem(
        id: 'ps_7',
        sector: DenverSector.personalSocial,
        title: 'Tepuk Tangan',
        instructions: 'Anak bertepuk tangan sendiri atau menirukan tepuk tangan.',
        p25: 6.0, p50: 8.0, p75: 10.0, p90: 12.0,
        reportableByParent: true,
        indexInSector: 6,
      ),
      const DenverItem(
        id: 'ps_8',
        sector: DenverSector.personalSocial,
        title: 'Menyatakan Keinginan',
        instructions: 'Anak menyatakan keinginan tanpa menangis (menunjuk/bersuara).',
        p25: 7.0, p50: 9.5, p75: 12.0, p90: 14.0,
        reportableByParent: true,
        indexInSector: 7,
      ),
      const DenverItem(
        id: 'ps_9',
        sector: DenverSector.personalSocial,
        title: 'Daag-daag Dengan Tangan',
        instructions: 'Anak melambaikan tangan saat berpisah atau menirukan lambaian.',
        p25: 7.5, p50: 10.0, p75: 12.5, p90: 14.5,
        reportableByParent: true,
        indexInSector: 8,
      ),
      const DenverItem(
        id: 'ps_10',
        sector: DenverSector.personalSocial,
        title: 'Main Bola Dengan Pemeriksa',
        instructions: 'Anak menggelindingkan atau melempar bola kembali ke pemeriksa.',
        p25: 8.0, p50: 10.5, p75: 13.0, p90: 15.0,
        reportableByParent: false,
        indexInSector: 9,
      ),
      const DenverItem(
        id: 'ps_11',
        sector: DenverSector.personalSocial,
        title: 'Menirukan Kegiatan',
        instructions: 'Anak menirukan kegiatan rumah tangga (mengepel, menyapu, dsb).',
        p25: 8.5, p50: 11.5, p75: 14.0, p90: 16.0,
        reportableByParent: true,
        indexInSector: 10,
      ),
      const DenverItem(
        id: 'ps_12',
        sector: DenverSector.personalSocial,
        title: 'Minum Dengan Cangkir',
        instructions: 'Anak minum dari cangkir/gelas tanpa banyak tumpah.',
        p25: 9.0, p50: 12.0, p75: 15.0, p90: 17.0,
        reportableByParent: true,
        indexInSector: 11,
      ),
      const DenverItem(
        id: 'ps_13',
        sector: DenverSector.personalSocial,
        title: 'Membantu Di Rumah',
        instructions: 'Anak membantu meletakkan barang/mainan jika diminta.',
        p25: 12.0, p50: 15.0, p75: 18.0, p90: 21.0,
        reportableByParent: true,
        indexInSector: 12,
      ),
      const DenverItem(
        id: 'ps_14',
        sector: DenverSector.personalSocial,
        title: 'Menggunakan Sendok/Garpu',
        instructions: 'Anak menggunakan sendok/garpu untuk membawa makanan ke mulut.',
        p25: 12.5, p50: 16.0, p75: 19.0, p90: 22.0,
        reportableByParent: true,
        indexInSector: 13,
      ),
      const DenverItem(
        id: 'ps_15',
        sector: DenverSector.personalSocial,
        title: 'Membuka Pakaian',
        instructions: 'Anak dapat melepas sendiri salah satu pakaian (kaos kaki, celana).',
        p25: 13.0, p50: 17.0, p75: 20.0, p90: 24.0,
        reportableByParent: true,
        indexInSector: 14,
      ),
      const DenverItem(
        id: 'ps_16',
        sector: DenverSector.personalSocial,
        title: 'Menyuapi Boneka',
        instructions: 'Anak menirukan memberi makan boneka atau orang lain.',
        p25: 14.0, p50: 18.0, p75: 22.0, p90: 26.0,
        reportableByParent: true,
        indexInSector: 15,
      ),
      const DenverItem(
        id: 'ps_17',
        sector: DenverSector.personalSocial,
        title: 'Memakai Baju Dengan Bantuan',
        instructions: 'Anak membantu memasukkan tangan/kaki saat dipakaikan baju.',
        p25: 18.0, p50: 22.0, p75: 26.0, p90: 30.0,
        reportableByParent: true,
        indexInSector: 16,
      ),
      const DenverItem(
        id: 'ps_18',
        sector: DenverSector.personalSocial,
        title: 'Gosok Gigi Dengan Bantuan',
        instructions: 'Anak menggosok gigi sendiri meski masih diarahkan orang tua.',
        p25: 18.5, p50: 23.0, p75: 27.0, p90: 32.0,
        reportableByParent: true,
        indexInSector: 17,
      ),
      const DenverItem(
        id: 'ps_19',
        sector: DenverSector.personalSocial,
        title: 'Cuci & Mengeringkan Tangan',
        instructions: 'Anak mencuci dan mengeringkan tangan dengan sabun/handuk.',
        p25: 19.0, p50: 24.0, p75: 30.0, p90: 36.0,
        reportableByParent: true,
        indexInSector: 18,
      ),
      const DenverItem(
        id: 'ps_20',
        sector: DenverSector.personalSocial,
        title: 'Menyebut Nama Teman',
        instructions: 'Anak dapat menyebutkan nama teman bermainnya.',
        p25: 22.0, p50: 28.0, p75: 34.0, p90: 42.0,
        reportableByParent: true,
        indexInSector: 19,
      ),
      const DenverItem(
        id: 'ps_21',
        sector: DenverSector.personalSocial,
        title: 'Memakai T-Shirt',
        instructions: 'Anak memakai kaos T-shirt sendiri tanpa dibantu.',
        p25: 24.0, p50: 30.0, p75: 38.0, p90: 46.0,
        reportableByParent: true,
        indexInSector: 20,
      ),
      const DenverItem(
        id: 'ps_22',
        sector: DenverSector.personalSocial,
        title: 'Berpakaian Tanpa Bantuan',
        instructions: 'Anak memakai baju lengkap (termasuk kancing/zipper) tanpa bantuan.',
        p25: 30.0, p50: 38.0, p75: 48.0, p90: 56.0,
        reportableByParent: true,
        indexInSector: 21,
      ),
      const DenverItem(
        id: 'ps_23',
        sector: DenverSector.personalSocial,
        title: 'Bermain Ular Tangga / Kartu',
        instructions: 'Anak memahami aturan giliran saat bermain permainan papan/kartu.',
        p25: 36.0, p50: 44.0, p75: 52.0, p90: 62.0,
        reportableByParent: true,
        indexInSector: 22,
      ),
      const DenverItem(
        id: 'ps_24',
        sector: DenverSector.personalSocial,
        title: 'Gosok Gigi Tanpa Bantuan',
        instructions: 'Anak menggosok gigi sendiri dengan bersih tanpa perlu dibantu.',
        p25: 38.0, p50: 46.0, p75: 54.0, p90: 64.0,
        reportableByParent: true,
        indexInSector: 23,
      ),
      const DenverItem(
        id: 'ps_25',
        sector: DenverSector.personalSocial,
        title: 'Mengambil Makan',
        instructions: 'Anak dapat menyiapkan/mengambil makanan sendiri ke piring.',
        p25: 42.0, p50: 50.0, p75: 58.0, p90: 68.0,
        reportableByParent: true,
        indexInSector: 24,
      ),
    ]);

    // =========================================================================
    // 2. ADAPTIF - MOTORIK HALUS
    // =========================================================================
    items.addAll([
      const DenverItem(
        id: 'fm_1',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mengikuti Ke Garis Tengah',
        instructions: 'Gerakkan benang merah di depan mata anak hingga garis tengah (90°).',
        p25: 0.1, p50: 0.5, p75: 1.0, p90: 1.5,
        reportableByParent: false,
        indexInSector: 0,
      ),
      const DenverItem(
        id: 'fm_2',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mengikuti Lewat Garis Tengah',
        instructions: 'Gerakkan benang melampaui garis tengah mata anak.',
        p25: 0.5, p50: 1.2, p75: 2.0, p90: 2.8,
        reportableByParent: false,
        indexInSector: 1,
      ),
      const DenverItem(
        id: 'fm_3',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Tangan Bersentuhan',
        instructions: 'Kedua tangan anak bertemu di garis tengah dada/perut.',
        p25: 1.2, p50: 2.0, p75: 3.0, p90: 3.8,
        reportableByParent: true,
        indexInSector: 2,
      ),
      const DenverItem(
        id: 'fm_4',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Memegang Rintik / Kecrekan',
        instructions: 'Sentuhkan kecrekan ke jemari anak. Anak memegang beberapa detik.',
        p25: 1.5, p50: 2.5, p75: 3.5, p90: 4.2,
        reportableByParent: false,
        indexInSector: 3,
      ),
      const DenverItem(
        id: 'fm_5',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mengamati Manik-Manik',
        instructions: 'Letakkan manik-manik di meja. Anak fokus mengamati.',
        p25: 2.0, p50: 3.0, p75: 4.0, p90: 5.0,
        reportableByParent: false,
        indexInSector: 4,
      ),
      const DenverItem(
        id: 'fm_6',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mengikuti 180°',
        instructions: 'Gerakkan benang merah berputar 180° lengkap dari kiri ke kanan.',
        p25: 2.2, p50: 3.5, p75: 4.5, p90: 5.5,
        reportableByParent: false,
        indexInSector: 5,
      ),
      const DenverItem(
        id: 'fm_7',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Meraih Mainan',
        instructions: 'Anak mengulurkan tangan dan berusaha memegang mainan.',
        p25: 2.5, p50: 4.0, p75: 5.0, p90: 6.0,
        reportableByParent: false,
        indexInSector: 6,
      ),
      const DenverItem(
        id: 'fm_8',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Memindahkan Kubus',
        instructions: 'Anak memindahkan kubus kayu dari satu tangan ke tangan lain.',
        p25: 5.0, p50: 6.2, p75: 7.5, p90: 8.5,
        reportableByParent: false,
        indexInSector: 7,
      ),
      const DenverItem(
        id: 'fm_9',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Memegang Manik-Manik',
        instructions: 'Anak mengambil manik-manik kecil dengan ibu jari dan jari-jari.',
        p25: 5.5, p50: 7.0, p75: 8.5, p90: 9.5,
        reportableByParent: false,
        indexInSector: 8,
      ),
      const DenverItem(
        id: 'fm_10',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Memegang Ibu Jari & Jari',
        instructions: 'Jepitan presisi (pincer grasp) menggunakan ujung ibu jari dan telunjuk.',
        p25: 6.5, p50: 8.0, p75: 9.5, p90: 10.8,
        reportableByParent: false,
        indexInSector: 9,
      ),
      const DenverItem(
        id: 'fm_11',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Membenturkan 2 Kubus',
        instructions: 'Anak memegang 2 kubus dan membenturkannya satu sama lain.',
        p25: 7.0, p50: 9.0, p75: 11.0, p90: 12.5,
        reportableByParent: false,
        indexInSector: 10,
      ),
      const DenverItem(
        id: 'fm_12',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menaruh Kubus Di Cangkir',
        instructions: 'Anak memasukkan kubus ke dalam cangkir jika dicontohkan.',
        p25: 8.0, p50: 10.0, p75: 12.0, p90: 14.0,
        reportableByParent: false,
        indexInSector: 11,
      ),
      const DenverItem(
        id: 'fm_13',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Ambil Manik-Manik Ditunjukkan',
        instructions: 'Anak mengambil manik-manik yang ditunjukkan tanpa ragu.',
        p25: 9.0, p50: 11.5, p75: 14.0, p90: 16.0,
        reportableByParent: false,
        indexInSector: 12,
      ),
      const DenverItem(
        id: 'fm_14',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mencorat-Coret',
        instructions: 'Berikan pensil dan kertas. Anak membuat goresan coretan sendiri.',
        p25: 12.0, p50: 14.5, p75: 17.5, p90: 20.0,
        reportableByParent: true,
        indexInSector: 13,
      ),
      const DenverItem(
        id: 'fm_15',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menara Dari 2 Kubus',
        instructions: 'Anak menyusun 2 kubus bertingkat tanpa jatuh.',
        p25: 13.5, p50: 16.5, p75: 20.0, p90: 23.0,
        reportableByParent: false,
        indexInSector: 14,
      ),
      const DenverItem(
        id: 'fm_16',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menara Dari 4 Kubus',
        instructions: 'Anak menyusun 4 kubus bertingkat.',
        p25: 16.0, p50: 19.0, p75: 23.0, p90: 27.0,
        reportableByParent: false,
        indexInSector: 15,
      ),
      const DenverItem(
        id: 'fm_17',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menara Dari 6 Kubus',
        instructions: 'Anak menyusun 6 kubus bertingkat.',
        p25: 18.0, p50: 22.0, p75: 26.0, p90: 31.0,
        reportableByParent: false,
        indexInSector: 16,
      ),
      const DenverItem(
        id: 'fm_18',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Meniru Garis Vertikal',
        instructions: 'Contohkan garis lurus ke bawah. Anak menirukan garis vertikal.',
        p25: 22.0, p50: 27.0, p75: 33.0, p90: 40.0,
        reportableByParent: false,
        indexInSector: 17,
      ),
      const DenverItem(
        id: 'fm_19',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menara Dari 8 Kubus',
        instructions: 'Anak menyusun 8 kubus bertingkat.',
        p25: 24.0, p50: 30.0, p75: 36.0, p90: 44.0,
        reportableByParent: false,
        indexInSector: 18,
      ),
      const DenverItem(
        id: 'fm_20',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menggoyangkan Ibu Jari',
        instructions: 'Kepalkan tangan, gerakkan ibu jari naik-turun. Anak menirukan.',
        p25: 26.0, p50: 32.0, p75: 40.0, p90: 48.0,
        reportableByParent: false,
        indexInSector: 19,
      ),
      const DenverItem(
        id: 'fm_21',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mencontoh + (Plus)',
        instructions: 'Tunjukkan gambar tanda tambah (+). Anak menggambar bentuk serupa.',
        p25: 32.0, p50: 40.0, p75: 48.0, p90: 56.0,
        reportableByParent: false,
        indexInSector: 20,
      ),
      const DenverItem(
        id: 'fm_22',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Memilih Garis Lebih Panjang',
        instructions: 'Tunjukkan 2 garis vertikal beda panjang. Anak menunjuk garis yang lebih panjang.',
        p25: 34.0, p50: 42.0, p75: 50.0, p90: 58.0,
        reportableByParent: false,
        indexInSector: 21,
      ),
      const DenverItem(
        id: 'fm_23',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menggambar Orang 3 Bagian',
        instructions: 'Minta anak menggambar orang. Gambar memiliki minimal 3 bagian badan.',
        p25: 36.0, p50: 44.0, p75: 52.0, p90: 60.0,
        reportableByParent: false,
        indexInSector: 22,
      ),
      const DenverItem(
        id: 'fm_24',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mencontoh O (Lingkaran)',
        instructions: 'Tunjukkan gambar lingkaran. Anak menggambar lingkaran tertutup.',
        p25: 38.0, p50: 46.0, p75: 54.0, p90: 62.0,
        reportableByParent: false,
        indexInSector: 23,
      ),
      const DenverItem(
        id: 'fm_25',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mencontoh Persegi Ditunjukkan',
        instructions: 'Peragakan cara menggambar persegi. Anak menirukan membuat segi empat.',
        p25: 42.0, p50: 50.0, p75: 58.0, p90: 66.0,
        reportableByParent: false,
        indexInSector: 24,
      ),
      const DenverItem(
        id: 'fm_26',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Menggambar Orang 6 Bagian',
        instructions: 'Gambar orang yang dibuat anak memiliki minimal 6 bagian badan.',
        p25: 44.0, p50: 52.0, p75: 60.0, p90: 68.0,
        reportableByParent: false,
        indexInSector: 25,
      ),
      const DenverItem(
        id: 'fm_27',
        sector: DenverSector.fineMotorAdaptive,
        title: 'Mencontoh Persegi',
        instructions: 'Tunjukkan kartu segi empat (tanpa peragaan). Anak menggambar segi empat.',
        p25: 48.0, p50: 56.0, p75: 64.0, p90: 72.0,
        reportableByParent: false,
        indexInSector: 26,
      ),
    ]);

    // =========================================================================
    // 3. BAHASA
    // =========================================================================
    items.addAll([
      const DenverItem(
        id: 'lang_1',
        sector: DenverSector.language,
        title: 'Bereaksi Terhadap Bel',
        instructions: 'Bunyikan bel halus dekat telinga anak. Anak kaget / mengedipkan mata.',
        p25: 0.1, p50: 0.4, p75: 0.8, p90: 1.2,
        reportableByParent: false,
        indexInSector: 0,
      ),
      const DenverItem(
        id: 'lang_2',
        sector: DenverSector.language,
        title: 'Bersuara (Ooo / Aah)',
        instructions: 'Anak mengeluarkan suara vokal panjang selain menangis.',
        p25: 0.5, p50: 1.0, p75: 1.8, p90: 2.5,
        reportableByParent: true,
        indexInSector: 1,
      ),
      const DenverItem(
        id: 'lang_3',
        sector: DenverSector.language,
        title: 'Tertawa',
        instructions: 'Anak tertawa terbahak-bahak saat diajak bercanda.',
        p25: 1.5, p50: 2.2, p75: 3.0, p90: 3.8,
        reportableByParent: true,
        indexInSector: 2,
      ),
      const DenverItem(
        id: 'lang_4',
        sector: DenverSector.language,
        title: 'Berteriak',
        instructions: 'Anak mengeluarkan suara teriakan gembira/nyaring.',
        p25: 1.8, p50: 2.8, p75: 3.8, p90: 4.8,
        reportableByParent: true,
        indexInSector: 3,
      ),
      const DenverItem(
        id: 'lang_5',
        sector: DenverSector.language,
        title: 'Menoleh Ke Arah Suara',
        instructions: 'Bicara dari samping. Anak memutar kepala mencari sumber suara.',
        p25: 2.5, p50: 3.8, p75: 5.0, p90: 6.2,
        reportableByParent: false,
        indexInSector: 4,
      ),
      const DenverItem(
        id: 'lang_6',
        sector: DenverSector.language,
        title: 'Menoleh Ke Bunyi Icik-Icik',
        instructions: 'Bunyikan kecrekan di luar bidang pandang. Anak menoleh ke bunyi.',
        p25: 3.0, p50: 4.5, p75: 6.0, p90: 7.5,
        reportableByParent: false,
        indexInSector: 5,
      ),
      const DenverItem(
        id: 'lang_7',
        sector: DenverSector.language,
        title: 'Meniru Bunyi Kata-Kata',
        instructions: 'Anak menirukan intonasi atau bunyi kata dari pemeriksa.',
        p25: 4.5, p50: 6.0, p75: 7.5, p90: 9.0,
        reportableByParent: true,
        indexInSector: 6,
      ),
      const DenverItem(
        id: 'lang_8',
        sector: DenverSector.language,
        title: 'Satu Silabel',
        instructions: 'Anak mengucapkan suku kata tunggal (ba, ma, da).',
        p25: 5.0, p50: 6.8, p75: 8.5, p90: 10.0,
        reportableByParent: true,
        indexInSector: 7,
      ),
      const DenverItem(
        id: 'lang_9',
        sector: DenverSector.language,
        title: 'Mengoceh (Babbling)',
        instructions: 'Anak mengoceh suku kata berulang (ba-ba-ba, ma-ma-ma).',
        p25: 5.5, p50: 7.2, p75: 9.0, p90: 10.5,
        reportableByParent: true,
        indexInSector: 8,
      ),
      const DenverItem(
        id: 'lang_10',
        sector: DenverSector.language,
        title: 'Kombinasi Silabel',
        instructions: 'Anak menggabungkan suku kata berbeda (da-ba, ma-ti).',
        p25: 6.0, p50: 8.0, p75: 10.0, p90: 11.5,
        reportableByParent: true,
        indexInSector: 9,
      ),
      const DenverItem(
        id: 'lang_11',
        sector: DenverSector.language,
        title: 'Papa/Mama Tidak Spesifik',
        instructions: 'Anak menyebut papa/mama tanpa ditujukan ke orang tertentu.',
        p25: 6.5, p50: 8.5, p75: 10.5, p90: 12.0,
        reportableByParent: true,
        indexInSector: 10,
      ),
      const DenverItem(
        id: 'lang_12',
        sector: DenverSector.language,
        title: 'Papa/Mama Spesifik',
        instructions: 'Anak memanggil papa/mama tepat pada orang tuanya.',
        p25: 8.5, p50: 11.0, p75: 13.0, p90: 14.5,
        reportableByParent: true,
        indexInSector: 11,
      ),
      const DenverItem(
        id: 'lang_13',
        sector: DenverSector.language,
        title: '1 Kata Berarti',
        instructions: 'Anak memiliki minimal 1 kata bermakna (selain mama/papa).',
        p25: 10.0, p50: 12.5, p75: 15.0, p90: 17.0,
        reportableByParent: true,
        indexInSector: 12,
      ),
      const DenverItem(
        id: 'lang_14',
        sector: DenverSector.language,
        title: '2 Kata Berarti',
        instructions: 'Anak memiliki minimal 2 kata bermakna.',
        p25: 11.5, p50: 14.0, p75: 17.0, p90: 19.5,
        reportableByParent: true,
        indexInSector: 13,
      ),
      const DenverItem(
        id: 'lang_15',
        sector: DenverSector.language,
        title: '3 Kata Berarti',
        instructions: 'Anak memiliki minimal 3 kata bermakna.',
        p25: 12.5, p50: 15.5, p75: 19.0, p90: 22.0,
        reportableByParent: true,
        indexInSector: 14,
      ),
      const DenverItem(
        id: 'lang_16',
        sector: DenverSector.language,
        title: '6 Kata Berarti',
        instructions: 'Anak mempunyai kosa kata minimal 6 kata.',
        p25: 15.0, p50: 18.5, p75: 22.5, p90: 26.0,
        reportableByParent: true,
        indexInSector: 15,
      ),
      const DenverItem(
        id: 'lang_17',
        sector: DenverSector.language,
        title: 'Menunjuk 2 Gambar',
        instructions: 'Tunjukkan lembar gambar. Anak menunjuk 2 gambar yang disebutkan.',
        p25: 16.0, p50: 19.5, p75: 24.0, p90: 28.0,
        reportableByParent: false,
        indexInSector: 16,
      ),
      const DenverItem(
        id: 'lang_18',
        sector: DenverSector.language,
        title: 'Kombinasi Kata',
        instructions: 'Anak menggabungkan 2 kata (misal: "mau minum", "papa pergi").',
        p25: 17.0, p50: 20.5, p75: 25.0, p90: 29.0,
        reportableByParent: true,
        indexInSector: 17,
      ),
      const DenverItem(
        id: 'lang_19',
        sector: DenverSector.language,
        title: 'Menyebut 1 Gambar',
        instructions: 'Anak dapat menamai minimal 1 gambar yang ditunjuk.',
        p25: 18.0, p50: 22.0, p75: 27.0, p90: 31.0,
        reportableByParent: false,
        indexInSector: 18,
      ),
      const DenverItem(
        id: 'lang_20',
        sector: DenverSector.language,
        title: 'Menunjuk Bagian Badan',
        instructions: 'Anak menunjuk 6 bagian badan sendiri saat diminta.',
        p25: 19.0, p50: 23.0, p75: 28.0, p90: 33.0,
        reportableByParent: true,
        indexInSector: 19,
      ),
      const DenverItem(
        id: 'lang_21',
        sector: DenverSector.language,
        title: 'Menunjuk 4 Gambar',
        instructions: 'Anak menunjuk 4 gambar dengan benar.',
        p25: 20.0, p50: 24.5, p75: 30.0, p90: 35.0,
        reportableByParent: false,
        indexInSector: 20,
      ),
      const DenverItem(
        id: 'lang_22',
        sector: DenverSector.language,
        title: 'Bicara Dengan Dimengerti',
        instructions: 'Bicara anak dimengerti setidaknya setengahnya oleh orang asing.',
        p25: 22.0, p50: 27.0, p75: 33.0, p90: 39.0,
        reportableByParent: true,
        indexInSector: 21,
      ),
      const DenverItem(
        id: 'lang_23',
        sector: DenverSector.language,
        title: 'Menyebut 4 Gambar',
        instructions: 'Anak menamai 4 gambar dengan benar.',
        p25: 24.0, p50: 29.0, p75: 36.0, p90: 42.0,
        reportableByParent: false,
        indexInSector: 22,
      ),
      const DenverItem(
        id: 'lang_24',
        sector: DenverSector.language,
        title: 'Mengetahui 2 Kegiatan',
        instructions: 'Tanyakan: "Apa yang kamu lakukan kalau lapar/haus?" Anak menjawab benar 2.',
        p25: 26.0, p50: 32.0, p75: 39.0, p90: 45.0,
        reportableByParent: false,
        indexInSector: 23,
      ),
      const DenverItem(
        id: 'lang_25',
        sector: DenverSector.language,
        title: 'Mengerti 2 Kata Sifat',
        instructions: 'Anak memahami makna dingin, laper, atau lelah.',
        p25: 28.0, p50: 34.0, p75: 42.0, p90: 48.0,
        reportableByParent: false,
        indexInSector: 24,
      ),
      const DenverItem(
        id: 'lang_26',
        sector: DenverSector.language,
        title: 'Menyebut 1 Warna',
        instructions: 'Anak dapat menamai 1 warna dengan tepat.',
        p25: 30.0, p50: 37.0, p75: 45.0, p90: 52.0,
        reportableByParent: false,
        indexInSector: 25,
      ),
      const DenverItem(
        id: 'lang_27',
        sector: DenverSector.language,
        title: 'Kegunaan 2 Benda',
        instructions: 'Tanyakan kegunaan cangkir, pensil, atau kursi. Anak menjawab 2.',
        p25: 32.0, p50: 39.0, p75: 47.0, p90: 54.0,
        reportableByParent: false,
        indexInSector: 26,
      ),
      const DenverItem(
        id: 'lang_28',
        sector: DenverSector.language,
        title: 'Menyebut 4 Warna',
        instructions: 'Anak menamai 4 warna utama (merah, biru, hijau, kuning).',
        p25: 34.0, p50: 42.0, p75: 50.0, p90: 58.0,
        reportableByParent: false,
        indexInSector: 27,
      ),
      const DenverItem(
        id: 'lang_29',
        sector: DenverSector.language,
        title: 'Mengerti 4 Kata Depan',
        instructions: 'Perintahkan meletakkan kubus di atas, di bawah, di depan, di belakang meja.',
        p25: 36.0, p50: 44.0, p75: 52.0, p90: 60.0,
        reportableByParent: false,
        indexInSector: 28,
      ),
      const DenverItem(
        id: 'lang_30',
        sector: DenverSector.language,
        title: 'Bicara Semua Dimengerti',
        instructions: 'Ucapan anak 100% dipahami oleh orang asing.',
        p25: 38.0, p50: 46.0, p75: 54.0, p90: 62.0,
        reportableByParent: true,
        indexInSector: 29,
      ),
      const DenverItem(
        id: 'lang_31',
        sector: DenverSector.language,
        title: 'Kegunaan 3 Benda',
        instructions: 'Anak menjelaskan fungsi 3 benda.',
        p25: 40.0, p50: 48.0, p75: 56.0, p90: 64.0,
        reportableByParent: false,
        indexInSector: 30,
      ),
      const DenverItem(
        id: 'lang_32',
        sector: DenverSector.language,
        title: 'Mengetahui 3 Kata Sifat',
        instructions: 'Anak menjawab 3 pertanyaan tentang kondisi fisik/perasaan.',
        p25: 42.0, p50: 50.0, p75: 58.0, p90: 66.0,
        reportableByParent: false,
        indexInSector: 31,
      ),
      const DenverItem(
        id: 'lang_33',
        sector: DenverSector.language,
        title: 'Mengartikan 5 Kata',
        instructions: 'Minta anak mendefinisikan 5 kata sederhana (bola, pisang, kuda, dll).',
        p25: 44.0, p50: 52.0, p75: 60.0, p90: 68.0,
        reportableByParent: false,
        indexInSector: 32,
      ),
      const DenverItem(
        id: 'lang_34',
        sector: DenverSector.language,
        title: 'Berlawanan 2',
        instructions: 'Lengkapi: "Api itu panas, es itu...". Jawab 2 lawan kata.',
        p25: 46.0, p50: 54.0, p75: 62.0, p90: 70.0,
        reportableByParent: false,
        indexInSector: 33,
      ),
      const DenverItem(
        id: 'lang_35',
        sector: DenverSector.language,
        title: 'Mengartikan 7 Kata',
        instructions: 'Anak mendefinisikan 7 kata dengan benar.',
        p25: 48.0, p50: 56.0, p75: 64.0, p90: 72.0,
        reportableByParent: false,
        indexInSector: 34,
      ),
      const DenverItem(
        id: 'lang_36',
        sector: DenverSector.language,
        title: 'Menghitung 5 Kubus',
        instructions: 'Anak menghitung 5 kubus secara berurutan dan menyebutkan jumlahnya.',
        p25: 50.0, p50: 58.0, p75: 66.0, p90: 72.0,
        reportableByParent: false,
        indexInSector: 35,
      ),
    ]);

    // =========================================================================
    // 4. MOTORIK KASAR
    // =========================================================================
    items.addAll([
      const DenverItem(
        id: 'gm_1',
        sector: DenverSector.grossMotor,
        title: 'Gerakan Seimbang',
        instructions: 'Gerakan simetris kedua lengan dan kaki saat telentang.',
        p25: 0.1, p50: 0.3, p75: 0.6, p90: 1.0,
        reportableByParent: false,
        indexInSector: 0,
      ),
      const DenverItem(
        id: 'gm_2',
        sector: DenverSector.grossMotor,
        title: 'Mengangkat Kepala',
        instructions: 'Saat telungkup, anak memutar/mengangkat kepala sedikit dari alas.',
        p25: 0.2, p50: 0.5, p75: 1.0, p90: 1.5,
        reportableByParent: false,
        indexInSector: 1,
      ),
      const DenverItem(
        id: 'gm_3',
        sector: DenverSector.grossMotor,
        title: 'Kepala Terangkat 45°',
        instructions: 'Saat telungkup, dada sedikit terangkat dan kepala tegak 45°.',
        p25: 0.5, p50: 1.0, p75: 1.8, p90: 2.5,
        reportableByParent: false,
        indexInSector: 2,
      ),
      const DenverItem(
        id: 'gm_4',
        sector: DenverSector.grossMotor,
        title: 'Kepala Terangkat 90°',
        instructions: 'Saat telungkup, kepala tegak 90° dan menahan posisi beberapa saat.',
        p25: 1.0, p50: 1.8, p75: 2.8, p90: 3.5,
        reportableByParent: false,
        indexInSector: 3,
      ),
      const DenverItem(
        id: 'gm_5',
        sector: DenverSector.grossMotor,
        title: 'Duduk Kepala Tegak',
        instructions: 'Pegang anak pada posisi duduk, kepala tegak tidak terkulai.',
        p25: 1.2, p50: 2.2, p75: 3.2, p90: 4.0,
        reportableByParent: false,
        indexInSector: 4,
      ),
      const DenverItem(
        id: 'gm_6',
        sector: DenverSector.grossMotor,
        title: 'Menumpu Beban Pada Kaki',
        instructions: 'Pegang badan anak dalam posisi berdiri, anak menahan sebagian beban.',
        p25: 1.8, p50: 3.0, p75: 4.2, p90: 5.2,
        reportableByParent: false,
        indexInSector: 5,
      ),
      const DenverItem(
        id: 'gm_7',
        sector: DenverSector.grossMotor,
        title: 'Dada Terangkat Menumpu 1 Lengan',
        instructions: 'Saat telungkup, menopang berat dengan kedua lengan bawah.',
        p25: 2.0, p50: 3.2, p75: 4.5, p90: 5.5,
        reportableByParent: false,
        indexInSector: 6,
      ),
      const DenverItem(
        id: 'gm_8',
        sector: DenverSector.grossMotor,
        title: 'Membalik',
        instructions: 'Anak berguling dari telungkup ke telentang atau sebaliknya.',
        p25: 2.2, p50: 3.5, p75: 5.0, p90: 6.0,
        reportableByParent: true,
        indexInSector: 7,
      ),
      const DenverItem(
        id: 'gm_9',
        sector: DenverSector.grossMotor,
        title: 'Bangkit Kepala Tegak',
        instructions: 'Tarik dari posisi telentang ke duduk, kepala ikut terangkat tegak.',
        p25: 2.8, p50: 4.0, p75: 5.2, p90: 6.2,
        reportableByParent: false,
        indexInSector: 8,
      ),
      const DenverItem(
        id: 'gm_10',
        sector: DenverSector.grossMotor,
        title: 'Duduk Tanpa Pegangan',
        instructions: 'Anak duduk sendiri tanpa ditopang minimal 5 detik.',
        p25: 4.8, p50: 6.0, p75: 7.2, p90: 8.0,
        reportableByParent: true,
        indexInSector: 9,
      ),
      const DenverItem(
        id: 'gm_11',
        sector: DenverSector.grossMotor,
        title: 'Berdiri Pegangan',
        instructions: 'Anak berdiri sambil berpegangan pada perabotan/kursi.',
        p25: 5.5, p50: 7.0, p75: 8.5, p90: 9.8,
        reportableByParent: true,
        indexInSector: 10,
      ),
      const DenverItem(
        id: 'gm_12',
        sector: DenverSector.grossMotor,
        title: 'Bangkit Untuk Berdiri',
        instructions: 'Anak berusaha berdiri sendiri dari posisi duduk.',
        p25: 6.5, p50: 8.2, p75: 10.0, p90: 11.5,
        reportableByParent: true,
        indexInSector: 11,
      ),
      const DenverItem(
        id: 'gm_13',
        sector: DenverSector.grossMotor,
        title: 'Bangkit Terus Duduk',
        instructions: 'Anak mengubah posisi telentang langsung ke posisi duduk.',
        p25: 6.8, p50: 8.5, p75: 10.2, p90: 11.8,
        reportableByParent: true,
        indexInSector: 12,
      ),
      const DenverItem(
        id: 'gm_14',
        sector: DenverSector.grossMotor,
        title: 'Berdiri 2 Detik',
        instructions: 'Anak berdiri lepas tanpa pegangan selama 2 detik.',
        p25: 8.0, p50: 10.0, p75: 12.0, p90: 13.5,
        reportableByParent: false,
        indexInSector: 13,
      ),
      const DenverItem(
        id: 'gm_15',
        sector: DenverSector.grossMotor,
        title: 'Berdiri Sendiri',
        instructions: 'Anak berdiri tegak sendiri selama 10 detik atau lebih.',
        p25: 9.0, p50: 11.2, p75: 13.2, p90: 14.5,
        reportableByParent: true,
        indexInSector: 14,
      ),
      const DenverItem(
        id: 'gm_16',
        sector: DenverSector.grossMotor,
        title: 'Membungkuk Kemudian Berdiri',
        instructions: 'Anak membungkuk mengambil mainan di lantai lalu berdiri kembali.',
        p25: 9.5, p50: 11.8, p75: 13.8, p90: 15.2,
        reportableByParent: true,
        indexInSector: 15,
      ),
      const DenverItem(
        id: 'gm_17',
        sector: DenverSector.grossMotor,
        title: 'Berjalan Dengan Baik',
        instructions: 'Anak berjalan seimbang tanpa sering jatuh.',
        p25: 11.0, p50: 12.5, p75: 14.0, p90: 15.5,
        reportableByParent: true,
        indexInSector: 16,
      ),
      const DenverItem(
        id: 'gm_18',
        sector: DenverSector.grossMotor,
        title: 'Berjalan Mundur',
        instructions: 'Anak berjalan mundur 2–3 langkah.',
        p25: 12.0, p50: 14.0, p75: 16.5, p90: 19.0,
        reportableByParent: true,
        indexInSector: 17,
      ),
      const DenverItem(
        id: 'gm_19',
        sector: DenverSector.grossMotor,
        title: 'Lari',
        instructions: 'Anak berlari tanpa terjatuh.',
        p25: 13.0, p50: 15.5, p75: 18.5, p90: 21.0,
        reportableByParent: true,
        indexInSector: 18,
      ),
      const DenverItem(
        id: 'gm_20',
        sector: DenverSector.grossMotor,
        title: 'Berjalan Naik Tangga',
        instructions: 'Anak berjalan naik tangga (boleh berpegangan).',
        p25: 14.0, p50: 17.0, p75: 20.0, p90: 23.0,
        reportableByParent: true,
        indexInSector: 19,
      ),
      const DenverItem(
        id: 'gm_21',
        sector: DenverSector.grossMotor,
        title: 'Menendang Bola Ke Depan',
        instructions: 'Anak menendang bola besar ke depan tanpa berpegangan.',
        p25: 15.0, p50: 18.0, p75: 21.5, p90: 24.5,
        reportableByParent: false,
        indexInSector: 20,
      ),
      const DenverItem(
        id: 'gm_22',
        sector: DenverSector.grossMotor,
        title: 'Melompat',
        instructions: 'Anak melompat angkat kedua kaki sekaligus di tempat.',
        p25: 16.0, p50: 20.0, p75: 24.0, p90: 28.0,
        reportableByParent: true,
        indexInSector: 21,
      ),
      const DenverItem(
        id: 'gm_23',
        sector: DenverSector.grossMotor,
        title: 'Melempar Bola Lengan Ke Atas',
        instructions: 'Anak melempar bola ke arah pemeriksa dengan gerakan dari atas bahu.',
        p25: 17.0, p50: 21.0, p75: 25.0, p90: 30.0,
        reportableByParent: false,
        indexInSector: 22,
      ),
      const DenverItem(
        id: 'gm_24',
        sector: DenverSector.grossMotor,
        title: 'Berdiri 1 Kaki 1 Detik',
        instructions: 'Anak berdiri seimbang dengan 1 kaki selama 1 detik.',
        p25: 18.0, p50: 24.0, p75: 30.0, p90: 36.0,
        reportableByParent: false,
        indexInSector: 23,
      ),
      const DenverItem(
        id: 'gm_25',
        sector: DenverSector.grossMotor,
        title: 'Melompat Jauh',
        instructions: 'Melompat ke depan melompati selembar kertas (20 cm).',
        p25: 22.0, p50: 28.0, p75: 34.0, p90: 40.0,
        reportableByParent: false,
        indexInSector: 24,
      ),
      const DenverItem(
        id: 'gm_26',
        sector: DenverSector.grossMotor,
        title: 'Berdiri 1 Kaki 2 Detik',
        instructions: 'Anak berdiri seimbang dengan 1 kaki selama 2 detik.',
        p25: 26.0, p50: 32.0, p75: 38.0, p90: 44.0,
        reportableByParent: false,
        indexInSector: 25,
      ),
      const DenverItem(
        id: 'gm_27',
        sector: DenverSector.grossMotor,
        title: 'Melompat Dengan 1 Kaki',
        instructions: 'Anak melompat (engklek) memakai 1 kaki.',
        p25: 30.0, p50: 36.0, p75: 42.0, p90: 48.0,
        reportableByParent: true,
        indexInSector: 26,
      ),
      const DenverItem(
        id: 'gm_28',
        sector: DenverSector.grossMotor,
        title: 'Berdiri 1 Kaki 3 Detik',
        instructions: 'Anak berdiri 1 kaki selama 3 detik.',
        p25: 32.0, p50: 40.0, p75: 48.0, p90: 54.0,
        reportableByParent: false,
        indexInSector: 27,
      ),
      const DenverItem(
        id: 'gm_29',
        sector: DenverSector.grossMotor,
        title: 'Berdiri 1 Kaki 4 Detik',
        instructions: 'Anak berdiri 1 kaki selama 4 detik.',
        p25: 34.0, p50: 42.0, p75: 50.0, p90: 58.0,
        reportableByParent: false,
        indexInSector: 28,
      ),
      const DenverItem(
        id: 'gm_30',
        sector: DenverSector.grossMotor,
        title: 'Berdiri 1 Kaki 5 Detik',
        instructions: 'Anak berdiri 1 kaki selama 5 detik.',
        p25: 36.0, p50: 44.0, p75: 52.0, p90: 60.0,
        reportableByParent: false,
        indexInSector: 29,
      ),
      const DenverItem(
        id: 'gm_31',
        sector: DenverSector.grossMotor,
        title: 'Berjalan Tumit Ke Jari Kaki',
        instructions: 'Anak berjalan lurus dengan tumit menyentuh ibu jari kaki depan.',
        p25: 38.0, p50: 46.0, p75: 54.0, p90: 62.0,
        reportableByParent: false,
        indexInSector: 30,
      ),
      const DenverItem(
        id: 'gm_32',
        sector: DenverSector.grossMotor,
        title: 'Berdiri 1 Kaki 6 Detik',
        instructions: 'Anak berdiri 1 kaki selama 6 detik.',
        p25: 40.0, p50: 48.0, p75: 56.0, p90: 64.0,
        reportableByParent: false,
        indexInSector: 31,
      ),
    ]);

    return items;
  }
}
